ANSI_ATTR_OVERLINE = b'53'

BOLD_BYTES = b'\x1b[1m'
ITALIC_BYTES = b'\x1b[3m'
SINGLE_UNDERLINE_BYTES = b'\x1b[4m'
DOUBLE_UNDERLINE_BYTES = b'\x1b[21m'
OVERLINE_BYTES = b'\x1b[53m'
INVERTED_BYTES = b'\x1b[7m'

NOT_INVERTED_BYTES = b'\x1b[27m'


ANSI_COLOR_BLACK = 0
